--1) 과목번호, 과목이름, 교수번호, 교수이름을 담을 수 있는 변수들을 선언하고 
--   유기화학 과목의 과목번호, 과목이름, 교수번호, 교수이름을 출력하세요.
DECLARE
    CNO    	 COURSE.CNO%TYPE;
    CNAME 	 COURSE.CNAME%TYPE;
    PNO    	 COURSE.PNO%TYPE;
    PNAME  	 PROFESSOR.PNAME%TYPE;
BEGIN
    -- 정보
    SELECT C.CNO, C.CNAME, P.PNO, P.PNAME
    INTO CNO, CNAME, PNO, PNAME
    FROM COURSE C
    JOIN PROFESSOR P ON C.PNO = P.PNO
    WHERE C.CNAME = '유기화학';
    -- 출력
    DBMS_OUTPUT.PUT_LINE('과목번호: ' || CNO);
    DBMS_OUTPUT.PUT_LINE('과목이름: ' || CNAME);
    DBMS_OUTPUT.PUT_LINE('교수번호: ' || PNO);
    DBMS_OUTPUT.PUT_LINE('교수이름: ' || PNAME);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('유기화학 과목을 찾을 수 없습니다.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('오류 발생: ' || SQLERRM);
END;

--2) 위 데이터들을 레코드로 선언하고 출력하세요.
CREATE TABLE COURSE_PROFESSOR_RECORD
	AS SELECT C.CNAME, C.CNO, P.PNO, P.PNAME
	FROM COURSE C JOIN PROFESSOR P ON P.PNO = C.PNO;

DECLARE
	TYPE COURSE_PROFESSOR_REC IS RECORD(
		CNAME 	COURSE.CNAME%TYPE,
		CNO	  	COURSE.CNO%TYPE,
		PNO		PROFESSOR.PNO%TYPE,
		PNAME	PROFESSOR.PNAME%TYPE
	);
	C_P_REC COURSE_PROFESSOR_REC;
BEGIN
	-- 정보
	SELECT CNAME, CNO, PNO, PNAME
	INTO C_P_REC
	FROM COURSE_PROFESSOR_RECORD
	WHERE CNAME = '유기화학';
    -- 출력
    DBMS_OUTPUT.PUT_LINE('과목번호: ' || C_P_REC.CNO);
    DBMS_OUTPUT.PUT_LINE('과목이름: ' || C_P_REC.CNAME);
    DBMS_OUTPUT.PUT_LINE('교수번호: ' || C_P_REC.PNO);
    DBMS_OUTPUT.PUT_LINE('교수이름: ' || C_P_REC.PNAME);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('유기화학 과목을 찾을 수 없습니다.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('오류 발생: ' || SQLERRM);
END;