--뷰 이름은 자유
--1) 학생의 평점 4.5 만점으로 환산된 정보를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_ST_CONVERT_AVR(
	ST_MAJOR,
	ST_NAME,
	ST_AVR
) AS (
	SELECT MAJOR, SNAME, ROUND((AVR * 4.5 / 4), 2) AS "ST_AVR" 
	FROM STUDENT
);

--2) 각 과목별 기말고사 평균 점수를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_COURSE_AVGRES(
	COURSE_NO,
	COURSE_NAME,
	AVGRES
) AS (
	SELECT SC.CNO, C.CNAME, ROUND(AVG(SC.RESULT), 2) AS "AVGRES"
	FROM COURSE C
	JOIN SCORE SC ON SC.CNO = C.CNO
	GROUP BY SC.CNO, C.CNAME
);

--3) 각 사원과 관리자(MGR)의 이름을 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_EMP_ENAME_MGR(
	ENAME,
	MRGNAME
) AS (
	SELECT E.ENAME, EM.ENAME
	FROM EMP E
	JOIN EMP EM ON E.MGR = EM.MGR
);

--4) 각 과목별 기말고사 평가 등급(A~F)까지와 해당 학생 정보를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_STINFO_RESGRADE(
	ST_NAME,
	COURSE_NAME,
	ST_GRADE
) AS (
	SELECT ST.SNAME, C.CNAME, SCG.GRADE
	FROM STUDENT ST
	JOIN SCORE SC ON SC.SNO = ST.SNO
	JOIN COURSE C ON C.CNO = SC.CNO
	JOIN SCGRADE SCG ON SC.RESULT BETWEEN SCG.LOSCORE AND SCG.HISCORE
);

--5) 물리학과 교수의 과목을 수강하는 학생의 명단을 검색할 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_PH_STINFO(
	ST_NAME,
	COURSE_NAME,
	PROFESSOR_NAME
) AS (
	SELECT ST.SNAME, C.CNAME, P.PNAME
	FROM STUDENT ST
	JOIN SCORE SC ON SC.SNO = ST.SNO
	JOIN COURSE C ON C.CNO = SC.CNO
	JOIN PROFESSOR P ON P.PNO = C.PNO
	WHERE P.SECTION = '물리'
);