--1) 4.5 환산 평점이 가장 높은 3인의 학생을 검색하세요.
SELECT ROWNUM, A.SNAME, A.CVT_AVR
FROM (
	SELECT SNAME, (AVR * 4.5 / 4) AS CVT_AVR
	FROM STUDENT
	WHERE AVR IS NOT NULL
	ORDER BY CVT_AVR DESC
)A
WHERE ROWNUM <= 3;

--2) 기말고사 과목별 평균이 높은 3과목을 검색하세요.
SELECT ROWNUM, A.CNAME, A.AVGRES
FROM (
	SELECT C.CNAME, ROUND(AVG(SC.RESULT), 2) AS AVGRES
	FROM SCORE SC
	JOIN COURSE C ON C.CNO = SC.CNO
	GROUP BY C.CNAME
	ORDER BY AVGRES DESC
)A
WHERE ROWNUM <= 3;

--3) 학과별, 학년별, 기말고사 평균이 순위 3까지를 검색하세요.(학과, 학년, 평균점수 검색)
SELECT ROWNUM, A.MAJOR, A.SYEAR, A.AVGRES
FROM(
	SELECT ST. MAJOR, ST. SYEAR, ROUND(AVG(SC.RESULT), 2) AS AVGRES
	FROM STUDENT ST
	JOIN SCORE SC ON ST.SNO = SC.SNO
	GROUP BY ST.MAJOR, ST.SYEAR
	ORDER BY AVGRES DESC
)A
WHERE ROWNUM <= 3;

--4) 기말고사 성적이 높은 과목을 담당하는 교수 3인을 검색하세요.(교수이름, 과목명, 평균점수 검색)
SELECT ROWNUM, A.PNAME, A.CNAME, A.AVGRES
FROM(
	SELECT P.PNAME, C.CNAME, ROUND(AVG(SC.RESULT), 2) AS AVGRES
	FROM PROFESSOR P
	JOIN COURSE C ON C.PNO = P.PNO
	JOIN SCORE SC ON SC.CNO = C.CNO
	GROUP BY P.PNAME, C.CNAME
	ORDER BY AVGRES DESC
)A
WHERE ROWNUM <= 3;

--5) 교수별로 현재 수강중인 학생의 수를 검색하세요.
SELECT PRO.PNAME, A.STUDENT_NUM
FROM (
	SELECT P.PNO, COUNT(SC.SNO) AS STUDENT_NUM
	FROM PROFESSOR P
	JOIN COURSE C ON P.PNO = C.PNO
	JOIN SCORE SC ON C.CNO = SC.CNO
	GROUP BY P.PNO
	ORDER BY P.PNO
)A
JOIN PROFESSOR PRO ON PRO.PNO = A.PNO
ORDER BY PRO.PNAME;
